# non-minecraft values
org.gradle.jvmargs=-Xmx2048M
jetbrainsAnnotationsVersion=23.0.0

# gradle kotlin jvm plugin breaks without this
kotlin.stdlib.default.dependency=false
kotlin.compiler.execution.strategy=in-process

# needed for mixins to work for forge
asmVersion=9.7.1

# mod info
modID=hexresearch
modVersion=1.0.2-indev
mavenGroup=name.dashkal.minecraft.hexresearch

# publishing
curseforgeId=
modrinthId=

# core
minecraftVersion=1.21.1
enabledPlatforms=neoforge
neoForgeVersion=21.1.111
forgeKotlinVersion=5.12.0
architecturyVersion=13.0.8
mixinExtrasVersion=0.5.0

# hex casting
hexcastingVersion=0.12.0-devel-pre-39
patchouliVersion=1.21.1-92-NEOFORGE
caelusVersion=7.0.1+1.21.1
inlineVersion=1.21.1-1.2.2-neoforge
clothConfigVersion=15.0.130
cardinalComponentsVersion=5.0.2
serializationHooksVersion=0.3.24
entityReachVersion=2.3.0
trinketsVersion=3.4.1
hexgloopVersion=0.2.0
wnboiVersion=0.0.4
