plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.2.21'
}
archivesBaseName = getArtifactId("common")

architectury {
    common(project.enabledPlatforms.split(",")) {
        it.platformPackage "neoforge", "forge"
    }
}

repositories {
    mavenCentral()
}

dependencies {
    modApi "dev.architectury:architectury:${project.architecturyVersion}"

    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8'
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.2' // for @Nonnull

    // mixin extras
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:${mixinExtrasVersion}"))

    compileOnly files(rootProject.file("hexcasting-neoforge-${minecraftVersion}-${hexcastingVersion}.jar"))
    testImplementation 'org.junit.jupiter:junit-jupiter:5.8.1'
    testCompileOnly files(rootProject.file("hexcasting-neoforge-${minecraftVersion}-${hexcastingVersion}.jar"))
    testRuntimeOnly files(rootProject.file("hexcasting-neoforge-${minecraftVersion}-${hexcastingVersion}.jar"))
}

test {
    useJUnitPlatform()
}

publishing {
    publications {
        mavenCommon(MavenPublication) {
            artifactId = project.archivesBaseName
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
    }
}
